-- Asset hierarchy: site -> zone -> asset -> sensor. Low-cardinality,
-- heavily cached configuration data.

CREATE TABLE IF NOT EXISTS site (
    site_id     uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name        text NOT NULL UNIQUE,
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS zone (
    zone_id     uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    site_id     uuid NOT NULL REFERENCES site(site_id),
    name        text NOT NULL,
    kind        text NOT NULL,               -- crusher_hall, conveyor_gallery, vent_shaft...
    UNIQUE (site_id, name)
);

-- Zone adjacency graph: the AI needs topology to compute isolation
-- blueprints ("closing zone A requires rerouting airflow via zone C").
CREATE TABLE IF NOT EXISTS zone_adjacency (
    zone_id     uuid NOT NULL REFERENCES zone(zone_id),
    adjacent_id uuid NOT NULL REFERENCES zone(zone_id),
    link_kind   text NOT NULL DEFAULT 'passage',  -- passage, conveyor, duct
    PRIMARY KEY (zone_id, adjacent_id),
    CHECK (zone_id <> adjacent_id)
);

CREATE TABLE IF NOT EXISTS asset (
    asset_id    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    zone_id     uuid NOT NULL REFERENCES zone(zone_id),
    name        text NOT NULL,
    kind        text NOT NULL,               -- ball_mill, conveyor_drive, vent_fan...
    -- How to shut this asset down + dependency ordering; consumed verbatim
    -- by the AI context builder.
    isolation_actions jsonb NOT NULL DEFAULT '[]',
    UNIQUE (zone_id, name)
);

DO $$ BEGIN
    CREATE TYPE sensor_kind AS ENUM
        ('gas_ch4','gas_co','o2','temp','vibration','pressure','airflow','dust_pm10','seismic');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE sensor_status AS ENUM ('active','degraded','maintenance','failed');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS sensor (
    sensor_id       uuid PRIMARY KEY,        -- UUIDv7, generated by the seeder
    asset_id        uuid NOT NULL REFERENCES asset(asset_id),
    zone_id         uuid NOT NULL REFERENCES zone(zone_id),
    kind            sensor_kind NOT NULL,
    unit            text NOT NULL,
    sample_hz       real NOT NULL DEFAULT 1.0,
    warn_threshold  double precision NOT NULL,
    crit_threshold  double precision NOT NULL,
    status          sensor_status NOT NULL DEFAULT 'active',
    created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS sensor_zone_idx ON sensor (zone_id);
CREATE INDEX IF NOT EXISTS sensor_asset_idx ON sensor (asset_id);
